
[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0


[keyboard]
bindings = [
  { key = "K", mods = "Command", action = "CreateNewWindow" },
]

[general]
# themes from https://github.com/alacritty/alacritty-theme

# import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["~/.config/alacritty/themes/themes/monokai.toml"]

# shell:
#  program: /usr/local/bin/fish
#  args:
#    - --command=tmux

[terminal.shell]
program = "/opt/homebrew/bin/pwsh"
# args = ["- --command=tmux"]

